= ADR 4: Use JUnit 5

== Context

When writing code, you should testIT. To run these test you need a
test runner. For Java there are many popular frameworks available.
First among them are:

* JUnit
* TestNG

JUnit is the de-factor standard when it comes to writing / executing
tests in Java. It is supported by all IDEs, Build Tools and most other
frameworks actually execute with JUnit as their foundation.

TestNG was an (over)reaction to some missing features in JUnit.
It has since been made obsolete with current versions of JUnit 4 and
even the first milestone release of JUnit 5 was better in all regards.

Some examples:

* JUnit 5 Extensions are enormously powerful - TestNG Listener are generally
the starting point for clever workarounds.
* TestNG recycles test instances which often has interesting side effects.
* Integration of TestNG with most IDE is rather clunky, especially in Eclipse.

== Decision

Since we are starting LivingDoc 2 on Java 8 and are always keep an eye
on the future, JUnit 5 is the way to go.

== Status

Proposed.

== Consequences

As long as there is no GA for JUnit 5 there are some limitations:

* IntelliJ is the only early adopter, Eclipse only has support in their
early access releases.
* Gradle support is currently only available via JUnit's plugin.
Official support should be available soon. The plugin is not that
powerful, but it is not very hard to implement a custom tests task.

All of these should be non-issues within the next 3 months.
